kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-to-configmap
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch", "update", "create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-to-configmap
subjects:
- kind: ServiceAccount
  name: consul-to-configmap
  namespace: default
roleRef:
  kind: ClusterRole
  name: consul-to-configmap
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-to-configmap
